spring:
  application:
    name: SampleData

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/sampledb?createDatabaseIfNotExist=true
    username: root
    password: password@123
    driver-class-name: com.mysql.cj.jdbc.Driver

